Week1 assignment
olgakahraman/node-express-course pull request #1
Opened 2024-06-19 01:55 UTC by olgakahraman

hello, this my first week assignment with 12 modules.

2024-06-19 15:17 UTC, redwan-faris requested changes
good job ogla
your code was perfect and I had fun reviewing it 
there is only two problems please check them 
1 - the output file should contain 3 lines in async 
2- the res.end error in http

2024-06-19 15:17 UTC, redwan-faris commented on 01-node-tutorial/answers/12-http.js
here its throw and error because its always go to the   res.end(`
       <h1>Error page</h1> 
       <p>We can't seem to find the page you are looking for</p>
       <a href="/">back home</a>
        `);
        
        
so you should put else statement

2024-06-19 15:17 UTC, redwan-faris commented on 01-node-tutorial/answers/11-fs-async.js
the code is correct but the file should contain 3 lines

2024-06-24 17:03 UTC, Austine105 commented
Hello @olgakahraman : I can see that you have made updates based on @redwan-faris feedback.
this is good to go ✅ 
you can add me as a review so I can approve the PR

2024-06-24 17:06 UTC, olgakahraman commented
Hello, nice to meet you. Thanx. How can I add you?

Пн, 24 июня 2024 г. в 13:03, Chukwuemeka ***@***.***>:

> Hello @olgakahraman <https://github.com/olgakahraman> : I can see that
> you have made updates based on @redwan-faris
> <https://github.com/redwan-faris> feedback.
> this is good to go ✅
> you can add me as a review so I can approve the PR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/olgakahraman/node-express-course/pull/1#issuecomment-2187024683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4EFV2QGA3KTD5RFSISQLFDZJBGNZAVCNFSM6AAAAABJRDIZQKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBXGAZDINRYGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-24 17:12 UTC, Austine105 commented
great to meet you too!

to add reviewer, go to the reviewers section on the top right corner of this page, click the settings icon and add me using my GitHub name(Austine105)

2024-06-24 19:07 UTC, merged